version: '3'

services:
  utmap-server-service:
    build: ./utmap-server
    volumes: 
      - ./utmap-server:/usr/src/app
    environment:
      - UTMAP_ENV=test
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - SKIP_DB_INIT=False
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5001
      - DEBUG=True
      - BUILDINGS=building_config.json
    ports:
      - 8081:5001
  
  mongo:
    image: mongo
    ports:
      - 9001:27017