version: '3'

services:
  utmap-server-service:
    build: ./utmap-server
    volumes: 
      - ./utmap-server:/usr/src/app
    environment:
      - UTMAP_ENV=dev
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - SKIP_DB_INIT=False
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5000
      - DEBUG=True
      - BUILDINGS=building_config.json
    ports:
      - 8080:5000
  
  mongo:
    image: mongo
    ports:
      - 9000:27017